name: T-Developer Deploy

on:
  workflow_run:
    workflows: ["T-Developer CI"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install boto3 aws-sam-cli
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Initialize registry
      run: |
        tdev init-registry
    - name: Package agents for deployment
      run: |
        mkdir -p deployment/agents
        python scripts/package_agents_for_deployment.py
    - name: Deploy to AWS Lambda
      run: |
        cd deployment
        sam build
        sam deploy --stack-name t-developer-agents --no-confirm-changeset --no-fail-on-empty-changeset
    - name: Update registry with deployment info
      run: |
        python scripts/update_registry_with_deployment_info.py
    - name: Notify Slack on successful deployment
      run: |
        python scripts/notify_slack.py --message "🚀 Deployment completed successfully" --status "success"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    - name: Notify Slack on deployment failure
      if: failure()
      run: |
        python scripts/notify_slack.py --message "❌ Deployment failed" --status "error"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}